### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by robsdedude** [Joshuaalbert/FairAsyncRLock#13]
This is a rather small note, but looking at `__aexit__`, there seems to be dead code.

```python
    async def __aexit__(self, exc_type, exc, tb):
        try:
            self.release()
        except asyncio.CancelledError as e:
            if self.is_owner():
                # If a cancellation happened during release, we force the current task to release.
                self._current_task_release()
            raise e
```
Since `self.release()` isn't async, it can't be canceled. And looking at `self.release()`, it doesn't seem to generate `asyncio.CancelledError`s itself. So the except block is not reachable, I think.

**Comment by Joshuaalbert** [comment]
Ah, this is remnant code, because previously I had `release` as an async function. So I think it's safe to remove this code. Good catch.
