### ISSUE TITLE
Potential deadlock

### ISSUE THREAD

**Issue by robsdedude** [Joshuaalbert/FairAsyncRLock#14]
By looking at the code, I suspect there's a potential for dead locks. I will try to come up with a test case that shows that and will let you know if I succeed. Until then, you might want to think about it and see if you come to the same conclusion.

Sequence leading to a dead lock (assume 4 tasks that take turns, e.g., only ever `await asyncio.sleep(0)` and the event loop is round robin):
 * Some task 1 acquires lock
 * There is a task 2 doing some (so far unrelated) things
 * Some task 3 tries to acquire the lock and ends up in the queue [L39](https://github.com/Joshuaalbert/FairAsyncRLock/blob/a96a1e3dd7c3d7a372f9976610921239c3cd7e9d/fair_async_rlock/fair_async_rlock.py#L39)
 * Task 3 awaits the event [L43](https://github.com/Joshuaalbert/FairAsyncRLock/blob/a96a1e3dd7c3d7a372f9976610921239c3cd7e9d/fair_async_rlock/fair_async_rlock.py#L43)
 * Some task 4 tries to acquire the lock (analog to the 2 steps above)
 * Task 1 releases the lock and sets the event which task 3 is waiting on [L57](https://github.com/Joshuaalbert/FairAsyncRLock/blob/a96a1e3dd7c3d7a372f9976610921239c3cd7e9d/fair_async_rlock/fair_async_rlock.py#L57)
 * Now it's taks 2's turn again and it decides to cancel task 3 for whatever reason and then task 2 ends
 * Task 3's turn: it was cancelled and removes itself from the queue [L47](https://github.com/Joshuaalbert/FairAsyncRLock/blob/a96a1e3dd7c3d7a372f9976610921239c3cd7e9d/fair_async_rlock/fair_async_rlock.py#L47) :warning:  even though the event was set and task 3 was scheduled to take the lock
 * Now it's task 4's turn... It will never be notified that the lock is actually free => :zap: dead lock

**Comment by Joshuaalbert** [comment]
@robsdedude Thanks kindly for your inspection, I'm back from holidays and am looking at this. 

Hmm, let me see if I get it. In your example if Task 1 releases the lock then Task 3 is freed on it's next round, but we get to Task 2 first, and it cancels Task 3. So when we get to Task 3, we get the cancel error before it takes ownership, queue removal, and Task 4 is left hanging.

I was able to create the scenario (I think) but actually this revealed **a different bug**! Event 3 is not in the queue when it tries to remove itself from it.

```python
@pytest.mark.asyncio
async def test_fair_async_rlock_deadlock_scenario():
    lock = FairAsyncRLock()

    # Use events to control the order of execution
    task1_aquired = asyncio.Event()
    task2_started = asyncio.Event()
    task3_started = asyncio.Event()
    task3_acquired = asyncio.Event()
    task4_acquired = asyncio.Event()
    task4_started = asyncio.Event()
    task1_done = asyncio.Event()

    async def task1():
        async with lock:
            task1_aquired.set()
            await task2_started.wait()
            await task3_started.wait() # wait until Task 3 in queue too
            await task4_started.wait() # wait until Task 4 in queue too
            await asyncio.sleep(0.1)  # make sure Task 4 gets in queue
            task1_done.set() # signal done before release, so Task 2 can cancel Task 3


    async def task2():
        await task1_aquired.wait()
        task2_started.set()
        await task1_done.wait() # Wait until Task 1 done then cancel Task 3
        t3.cancel()

    async def task3():
        await task2_started.wait()
        task3_started.set()
        async with lock: # now in queue, waiting
            task3_acquired.set() # Should not get reached, because Task 3 will be cancelled always

    async def task4():
        await task3_started.wait()
        await asyncio.sleep(0.1) # make sure Task 3 gets in queue first
        task4_started.set()
        async with lock: # it's not in queue, just after Task 3, and waiting
            task4_acquired.set()

    t1 = asyncio.create_task(task1())
    t2 = asyncio.create_task(task2())
    t3 = asyncio.create_task(task3())
    t4 = asyncio.create_task(task4())

    await t1
    await t2
    await t3 # Here we get ValueError: <asyncio.locks.Event object at 0x7f419f7dba90 [set]> is not in deque

    # Task 3 would never acquire
    assert not task3_acquired.is_set()
    # Task 4 should not deadlock. It should be able to acquire the locks
    await asyncio.wait([t4], timeout=1)
    assert task4_acquired.is_set()
```

**Comment by Joshuaalbert** [comment]
Solution (to both bugs) is to replace the queue removal at https://github.com/Joshuaalbert/FairAsyncRLock/blob/main/fair_async_rlock/fair_async_rlock.py#L47 with 

```python
self._owner = me
self._count = 1
self._current_task_release()
```
